apiVersion: apps/v1
kind: Deployment
metadata:
  name: zturn-frontend
  namespace: 11lxf-uat
  labels:
    app: zturn-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zturn-frontend
  template:
    metadata:
      name: zturn-frontend
      labels:
        app: zturn-frontend
    spec:
      terminationGracePeriodSeconds: 1
      containers:
        - name: zturn-frontend
          image: dockerhub.shawf.me/11lxf/zturn-frontend:1.0.0
          # 测试环境tag一样，每次都拉取最新的镜像
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            limits:
              cpu: '1'
              memory: '1Gi'
            requests:
              cpu: '50m'
              memory: '128Mi'
          env:
            - name: TZ
              value: "Asia/Shanghai"
            - name: PUID
              value: "3000"
            - name: PGID
              value: "3000"
          volumeMounts:
            - name: logs-data
              mountPath: /var/log/nginx
              subPath: zturn-frontend
      restartPolicy: Always
      volumes:
        - name: logs-data
          persistentVolumeClaim:
            claimName: logs-claim
