apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      app: ${SERVICE_NAME}

images:
  - name: dockerhub.shawf.me/11lxf/zturn-frontend
    newName: dockerhub.shawf.me/${REPO}/${SERVICE_NAME}
    newTag: ${VERSION}
